version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  server: #name of the server service
    build: . # specify the directory of the Dockerfile
    ports:
      - "8000:8000" #specify ports forewarding
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: postgres # specify image to build container from
    ports:
      - "5433:5432" # specify port forewarding
    env_file:
      - postgres-variables.env