version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  server: #name of the server service
    build: # specify the directory of the Dockerfile
      context: ./server
      dockerfile: dockerfile.server
    ports:
      - "8000:8000" #specify ports forewarding
    links:
      - database # link this service to the database service
    volumes:
      - ./server:/usr/src/app/server
      - ./client/resources:/usr/src/app/client/resources
      - wwwroot:/usr/src/app/client/dist

  database: # name of the third service
    image: postgres # specify image to build container from
    ports:
      - "5433:5432" # specify port forewarding
    env_file:
      - server/postgres-variables.env #specify variables for running postgres - username, password and dbname

  webpack:
    build:
        context: ./client
        dockerfile: dockerfile.webpack
    image: my-webpack
    container_name: my-webpack-container
    ports:
      - "35729:35729" # for live reload
    volumes:
      - ./client:/app # create volume linking root location on host to /app in container
      - wwwroot:/app/dist #wwwroot available in container at /client/dist

volumes:
  wwwroot:
    driver: local